// Icon vocabulary for design tools: the lucide icons AtelierHQ's own screens
// import, exposed on the kit's global (window.AtelierHQ.PlusIcon, ...) via
// cfg.extraEntries. A design agent consuming the bundle has no bundler, so it
// cannot `import` from "lucide-react" the way the app does. Every name ends in
// "Icon" so none can collide with a kit component (Calendar, Table, Command).
// Regenerate the list when the app starts using new icons.
export {
  AlertCircleIcon,
  AlertTriangleIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  BanknoteIcon,
  BarChart3Icon,
  BoxesIcon,
  CalendarClockIcon,
  CalendarDaysIcon,
  CheckCircle2Icon,
  CheckIcon,
  CheckSquareIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleCheckIcon,
  CircleIcon,
  ClipboardListIcon,
  ClockIcon,
  CompassIcon,
  CreditCardIcon,
  DownloadIcon,
  FileTextIcon,
  GripVerticalIcon,
  InfoIcon,
  LayoutDashboardIcon,
  Loader2Icon,
  LogOutIcon,
  MailIcon,
  MessageCircleIcon,
  MinusIcon,
  MoonIcon,
  MoreHorizontalIcon,
  OctagonXIcon,
  PackageMinusIcon,
  PanelLeftIcon,
  PencilIcon,
  PhoneIcon,
  PlusIcon,
  ReceiptIcon,
  RotateCcwIcon,
  RulerIcon,
  ScissorsIcon,
  ScissorsLineDashedIcon,
  SearchIcon,
  SettingsIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SlidersHorizontalIcon,
  SplineIcon,
  StoreIcon,
  SunIcon,
  Trash2Icon,
  TrendingDownIcon,
  TrendingUpIcon,
  TriangleAlertIcon,
  TruckIcon,
  UserCheckIcon,
  UserIcon,
  UsersIcon,
  WalletIcon,
  XIcon,
} from "lucide-react";
